package com.example.envelopebudget.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

private val light_primary = Color(0xFF385ba8)
private val light_onPrimary = Color(0xFFffffff)
private val light_primaryContainer = Color(0xFFd9e2ff)
private val light_onPrimaryContainer = Color(0xFF001848)
private val light_secondary = Color(0xFF585e71)
private val light_onSecondary = Color(0xFFffffff)
private val light_secondaryContainer = Color(0xFFdce2f9)
private val light_onSecondaryContainer = Color(0xFF151b2c)
private val light_tertiary = Color(0xFF7f5700)
private val light_onTertiary = Color(0xFFffffff)
private val light_tertiaryContainer = Color(0xFFffdea7)
private val light_onTertiaryContainer = Color(0xFF281900)
private val light_error = Color(0xFFba1b1b)
private val light_errorContainer = Color(0xFFffdad4)
private val light_onError = Color(0xFFffffff)
private val light_onErrorContainer = Color(0xFF410001)
private val light_background = Color(0xFFfdfbff)
private val light_onBackground = Color(0xFF1b1b1e)
private val light_surface = Color(0xFFfdfbff)
private val light_onSurface = Color(0xFF1b1b1e)
private val light_surfaceVariant = Color(0xFFe2e2ec)
private val light_onSurfaceVariant = Color(0xFF44464e)
private val light_outline = Color(0xFF757780)
private val light_inverseOnSurface = Color(0xFFf2f0f5)
private val light_inverseSurface = Color(0xFF303033)
private val light_inversePrimary = Color(0xFFb0c6ff)

private val dark_primary = Color(0xFFb0c6ff)
private val dark_onPrimary = Color(0xFF002b73)
private val dark_primaryContainer = Color(0xFF1c438f)
private val dark_onPrimaryContainer = Color(0xFFd9e2ff)
private val dark_secondary = Color(0xFFc0c6dd)
private val dark_onSecondary = Color(0xFF2a3041)
private val dark_secondaryContainer = Color(0xFF404658)
private val dark_onSecondaryContainer = Color(0xFFdce2f9)
private val dark_tertiary = Color(0xFFfabc49)
private val dark_onTertiary = Color(0xFF432c00)
private val dark_tertiaryContainer = Color(0xFF604100)
private val dark_onTertiaryContainer = Color(0xFFffdea7)
private val dark_error = Color(0xFFffb4a9)
private val dark_errorContainer = Color(0xFF930006)
private val dark_onError = Color(0xFF680003)
private val dark_onErrorContainer = Color(0xFFffdad4)
private val dark_background = Color(0xFF1b1b1e)
private val dark_onBackground = Color(0xFFe4e2e6)
private val dark_surface = Color(0xFF1b1b1e)
private val dark_onSurface = Color(0xFFe4e2e6)
private val dark_surfaceVariant = Color(0xFF44464e)
private val dark_onSurfaceVariant = Color(0xFFc5c6d0)
private val dark_outline = Color(0xFF8f909a)
private val dark_inverseOnSurface = Color(0xFF1b1b1e)
private val dark_inverseSurface = Color(0xFFe4e2e6)
private val dark_inversePrimary = Color(0xFF385ba8)

val LightThemeColors = lightColorScheme(
    primary = light_primary,
    onPrimary = light_onPrimary,
    primaryContainer = light_primaryContainer,
    onPrimaryContainer = light_onPrimaryContainer,
    secondary = light_secondary,
    onSecondary = light_onSecondary,
    secondaryContainer = light_secondaryContainer,
    onSecondaryContainer = light_onSecondaryContainer,
    tertiary = light_tertiary,
    onTertiary = light_onTertiary,
    tertiaryContainer = light_tertiaryContainer,
    onTertiaryContainer = light_onTertiaryContainer,
    error = light_error,
    errorContainer = light_errorContainer,
    onError = light_onError,
    onErrorContainer = light_onErrorContainer,
    background = light_background,
    onBackground = light_onBackground,
    surface = light_surface,
    onSurface = light_onSurface,
    surfaceVariant = light_surfaceVariant,
    onSurfaceVariant = light_onSurfaceVariant,
    outline = light_outline,
    inverseOnSurface = light_inverseOnSurface,
    inverseSurface = light_inverseSurface,
    inversePrimary = light_inversePrimary
)
val DarkThemeColors = darkColorScheme(
    primary = dark_primary,
    onPrimary = dark_onPrimary,
    primaryContainer = dark_primaryContainer,
    onPrimaryContainer = dark_onPrimaryContainer,
    secondary = dark_secondary,
    onSecondary = dark_onSecondary,
    secondaryContainer = dark_secondaryContainer,
    onSecondaryContainer = dark_onSecondaryContainer,
    tertiary = dark_tertiary,
    onTertiary = dark_onTertiary,
    tertiaryContainer = dark_tertiaryContainer,
    onTertiaryContainer = dark_onTertiaryContainer,
    error = dark_error,
    errorContainer = dark_errorContainer,
    onError = dark_onError,
    onErrorContainer = dark_onErrorContainer,
    background = dark_background,
    onBackground = dark_onBackground,
    surface = dark_surface,
    onSurface = dark_onSurface,
    surfaceVariant = dark_surfaceVariant,
    onSurfaceVariant = dark_onSurfaceVariant,
    outline = dark_outline,
    inverseOnSurface = dark_inverseOnSurface,
    inverseSurface = dark_inverseSurface,
    inversePrimary = dark_inversePrimary
)
